version: '3'

tasks:
  consul:
    cmds: 
      - docker run
        -d -p 8500:8500 -p 8600:8600/udp --name=badger
        consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

  p2p-rpc:
    cmds:
      - protoc
        --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        p2p-rpc/service/service.proto